variables:
  MSBUILD: 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\MSBuild.exe'
  NUGET: 'NuGet\nuget.exe'
  VINTER_SLN: 'VinteR\VinteR.sln'

stages:
  - build

before_script:
  - echo "Restoring NuGet Packages..."
  - '& $env:NUGET restore $env:VINTER_SLN'

build:
 stage: build
 script:
  - '& $env:MSBUILD $env:VINTER_SLN /t:Clean,ReBuild /p:Configuration=Debug'
  - '& $env:MSBUILD $env:VINTER_SLN /t:ReBuild /p:Configuration=Release'
 only:
   - development