variables:
  MSBUILD_PATH: 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\MSBuild.exe'
  NUGET_PATH: 'NuGet\nuget.exe'
  VINTER_SLN_PATH: 'VinteR\VinteR.sln'
  NUNIT_PATH: 'VinteR\packages\NUnit.ConsoleRunner.3.8.0\tools\nunit3-console.exe'
  TEST_FOLDER: 'VinteR.Tests\bin\x64\Release'

stages:
  - build
  - test

before_script:
  - echo "Restoring NuGet Packages..."
  - '& $env:NUGET_PATH restore $env:VINTER_SLN_PATH'

build:
  stage: build
  script:
    - echo "Building debug and release..."
    - '& $env:MSBUILD_PATH $env:VINTER_SLN_PATH /t:Clean,ReBuild /p:Configuration=Debug'
    - '& $env:MSBUILD_PATH $env:VINTER_SLN_PATH /t:ReBuild /p:Configuration=Release'

test:
  stage: test
  script:
    - echo "Running tests..."
    - 'xcopy VinteR\vinter.config.json .'
    - 'xcopy VinteR\vinter.config.schema.json .'
    - 'xcopy VinteR\vinter.config.local.json .'
    - '& $env:NUNIT_PATH $env:TEST_FOLDER\VinteR.Tests.dll"'